
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '19.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @testim/testim-cli
    testim \
    --token $(TOKEN) \
    --project $(PROJECT) \
    --name "Login" \
    --grid $(GRID) \
    --report-file testim-tests-report.xml
  displayName: 'npm install testim-cli and run tests'

- task: PublishTestResults@2
  displayName: 'publish testim test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/testim-tests-report.xml'
